// Writes app/theme.generated.css: the Cloudscape overrides that turn the stock theme into
// the AWS console's. Runs before `dev` and `build`, so the styles are part of the first
// paint instead of being applied by JavaScript after it.
import { writeFileSync } from "node:fs";
import { registerHooks } from "node:module";

// Cloudscape ships ES modules written for bundlers: their relative imports have no file
// extension. Teach Node to resolve those so the theme generator can run in a plain script.
registerHooks({
  resolve(specifier, context, nextResolve) {
    try {
      return nextResolve(specifier, context);
    } catch (error) {
      if (specifier.startsWith(".")) {
        for (const suffix of [".js", "/index.js"]) {
          try {
            return nextResolve(specifier + suffix, context);
          } catch {
            // try the next candidate
          }
        }
      }
      throw error;
    }
  },
});

const { generateThemeStylesheet } = await import("@cloudscape-design/components/theming");

const ORANGE = "#ff9900";
const ORANGE_PRESSED = "#fa6f00";
const INK = "#0f141a";

// The console is stock Cloudscape with one visible difference: primary buttons are orange
// with dark text, in light and dark mode. Values come from the console's CSS variables.
const theme = {
  tokens: {
    colorBackgroundButtonPrimaryDefault: ORANGE,
    colorBackgroundButtonPrimaryHover: ORANGE_PRESSED,
    colorBackgroundButtonPrimaryActive: ORANGE_PRESSED,
    colorBorderButtonPrimaryDefault: ORANGE,
    colorBorderButtonPrimaryHover: ORANGE_PRESSED,
    colorBorderButtonPrimaryActive: ORANGE_PRESSED,
    colorTextButtonPrimaryDefault: INK,
    colorTextButtonPrimaryHover: INK,
    colorTextButtonPrimaryActive: INK,
  },
};

const banner = "/* Generated by scripts/generate-theme.mjs. Do not edit. */\n";
writeFileSync(
  new URL("../app/theme.generated.css", import.meta.url),
  banner + generateThemeStylesheet({ theme }) + "\n",
);
