/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness and database check */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in and start a session
         * @description Repeated failures from one address are throttled: the answer is then 429 with a `Retry-After` header, whether or not the account exists.
         *
         *     With `R53_DEMO_SANDBOX` on, signing in to the demo account opens the caller's own sandbox, a private copy of the sample zones remembered by a second cookie.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End the current session */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in user */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/published-credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Credentials the sign-in page may show
         * @description Lets the sign-in page of a public deployment show how to get in. Returns 404 when `R53_DEMO_CREDENTIALS_PUBLIC` is off.
         */
        get: operations["published_credentials"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hostedzones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List hosted zones */
        get: operations["list_hosted_zones"];
        put?: never;
        /**
         * Create a hosted zone
         * @description Also creates the apex NS and SOA record sets, as Route 53 does.
         */
        post: operations["create_hosted_zone"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hostedzones/{zone_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a hosted zone */
        get: operations["get_hosted_zone"];
        put?: never;
        post?: never;
        /**
         * Delete a hosted zone
         * @description Fails with `HostedZoneNotEmpty` while the zone has records besides the apex NS and SOA.
         */
        delete: operations["delete_hosted_zone"];
        options?: never;
        head?: never;
        /**
         * Edit a hosted zone
         * @description The description, the tags and, for a private zone, the VPC associations can be changed after a zone is created. Omitted fields keep their value; the edit is applied as a whole or not at all.
         */
        patch: operations["update_hosted_zone"];
        trace?: never;
    };
    "/api/v1/hostedzones/{zone_id}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List a zone's tags */
        get: operations["list_tags"];
        /** Replace a zone's tags */
        put: operations["replace_tags"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hostedzones/{zone_id}/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the records of a hosted zone */
        get: operations["list_records"];
        put?: never;
        /** Create a record */
        post: operations["create_record"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hostedzones/{zone_id}/records:batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply a change batch atomically
         * @description CREATE, UPSERT and DELETE changes run in order in one transaction, like `ChangeResourceRecordSets`. If any change is invalid, none is applied and every failure is listed in `details` with the index of its change.
         *
         *     The answer carries the change's `id` and its `status`, which starts as `PENDING`; `GET /changes/{change_id}` reports it afterwards.
         */
        post: operations["change_records"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hostedzones/{zone_id}/records/{record_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a record */
        get: operations["get_record"];
        put?: never;
        post?: never;
        /**
         * Delete a record
         * @description The apex NS and SOA records cannot be deleted.
         */
        delete: operations["delete_record"];
        options?: never;
        head?: never;
        /**
         * Edit a record
         * @description Omitted fields keep their value. The apex NS and SOA records can be edited but not renamed or retyped.
         */
        patch: operations["update_record"];
        trace?: never;
    };
    "/api/v1/hostedzones/{zone_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export a hosted zone
         * @description `bind` returns a zone file; `json` returns the zone and its record sets in the shape of the AWS CLI's `list-resource-record-sets`.
         */
        get: operations["export_zone"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hostedzones/{zone_id}/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import records from a BIND zone file
         * @description With `dry_run` (the default) the file is parsed and validated and a preview is returned. Without it the records are created in one atomic change batch; the apex NS and SOA in the file are skipped.
         */
        post: operations["import_zone_file"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/changes/{change_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the status of a change
         * @description Modelled on Route 53's `GetChange`. A change to a zone's records is `PENDING` for `R53_CHANGE_PROPAGATION_SECONDS` after it was saved and `INSYNC` from then on. The status is simulated: the records are final as soon as the change request returns, and nothing is propagated because no DNS is served. Changes older than a day are forgotten once their zone changes again.
         */
        get: operations["get_change"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AliasTarget */
        AliasTarget: {
            /** Dns Name */
            dns_name: string;
            /** Hosted Zone Id */
            hosted_zone_id: string;
            /**
             * Evaluate Target Health
             * @default false
             */
            evaluate_target_health?: boolean;
        };
        /** Change */
        Change: {
            action: components["schemas"]["ChangeAction"];
            record_set: components["schemas"]["RecordSetInput"];
        };
        /**
         * ChangeAction
         * @enum {string}
         */
        ChangeAction: "CREATE" | "UPSERT" | "DELETE";
        /** ChangeBatchRequest */
        ChangeBatchRequest: {
            /**
             * Comment
             * @default
             */
            comment?: string;
            /** Changes */
            changes: components["schemas"]["Change"][];
        };
        /** ChangeBatchResult */
        ChangeBatchResult: {
            /**
             * Id
             * @example C2682N5HXP0BZ4
             */
            id: string;
            /** @description `PENDING` for a few seconds after the change is saved, then `INSYNC`. The status is simulated: the change is in the database at once and no DNS is served. */
            status: components["schemas"]["ChangeStatus"];
            /** Comment */
            comment: string;
            /**
             * Submitted At
             * Format: date-time
             */
            submitted_at: string;
            /** Created */
            created: number;
            /** Updated */
            updated: number;
            /** Deleted */
            deleted: number;
            /**
             * Record Sets
             * @description Record sets created or updated
             */
            record_sets: components["schemas"]["RecordSetOut"][];
        };
        /**
         * ChangeInfo
         * @description The status of a change, in the shape of Route 53's ``ChangeInfo``.
         */
        ChangeInfo: {
            /**
             * Id
             * @example C2682N5HXP0BZ4
             */
            id: string;
            /** @description `PENDING` for a few seconds after the change is saved, then `INSYNC`. The status is simulated: the change is in the database at once and no DNS is served. */
            status: components["schemas"]["ChangeStatus"];
            /** Comment */
            comment: string;
            /**
             * Submitted At
             * Format: date-time
             */
            submitted_at: string;
        };
        /**
         * ChangeStatus
         * @enum {string}
         */
        ChangeStatus: "PENDING" | "INSYNC";
        /** ErrorDetail */
        ErrorDetail: {
            /**
             * Field
             * @description Request field the problem relates to
             */
            field?: string | null;
            /**
             * Index
             * @description Position of the failing batch change
             */
            index?: number | null;
            /**
             * Line
             * @description Zone file line the problem relates to
             */
            line?: number | null;
            /** Message */
            message: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            /**
             * Code
             * @example NoSuchHostedZone
             */
            code: string;
            /** Message */
            message: string;
            /**
             * Details
             * @default []
             */
            details?: components["schemas"]["ErrorDetail"][];
        };
        /**
         * FailoverRole
         * @enum {string}
         */
        FailoverRole: "PRIMARY" | "SECONDARY";
        /** GeoLocation */
        GeoLocation: {
            /** Continent Code */
            continent_code?: string | null;
            /** Country Code */
            country_code?: string | null;
            /** Subdivision Code */
            subdivision_code?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthStatus */
        HealthStatus: {
            /** Status */
            status: string;
            /** Database */
            database: string;
        };
        /** HostedZoneCreate */
        HostedZoneCreate: {
            /**
             * Name
             * @example example.com
             */
            name: string;
            /**
             * Description
             * @default
             */
            description?: string;
            /** @default public */
            type?: components["schemas"]["ZoneType"];
            /**
             * Vpcs
             * @default []
             */
            vpcs?: components["schemas"]["VpcAssociation"][];
            /**
             * Tags
             * @default []
             */
            tags?: components["schemas"]["Tag"][];
        };
        /** HostedZoneDetail */
        HostedZoneDetail: {
            /**
             * Id
             * @example Z0123456789ABCDEFGHIJ
             */
            id: string;
            /**
             * Name
             * @description Canonical zone name with trailing dot
             * @example example.com.
             */
            name: string;
            type: components["schemas"]["ZoneType"];
            /** Description */
            description: string;
            /** Created By */
            created_by: string;
            /** Record Count */
            record_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Caller Reference */
            caller_reference: string;
            /** Name Servers */
            name_servers: string[];
            /** Vpcs */
            vpcs: components["schemas"]["VpcAssociation"][];
            /** Tags */
            tags: components["schemas"]["Tag"][];
        };
        /** HostedZoneSummary */
        HostedZoneSummary: {
            /**
             * Id
             * @example Z0123456789ABCDEFGHIJ
             */
            id: string;
            /**
             * Name
             * @description Canonical zone name with trailing dot
             * @example example.com.
             */
            name: string;
            type: components["schemas"]["ZoneType"];
            /** Description */
            description: string;
            /** Created By */
            created_by: string;
            /** Record Count */
            record_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * HostedZoneUpdate
         * @description Partial update; omitted fields keep their current value.
         */
        HostedZoneUpdate: {
            /** Description */
            description?: string | null;
            /**
             * Tags
             * @description Replaces every tag of the zone
             */
            tags?: components["schemas"]["Tag"][] | null;
            /**
             * Vpcs
             * @description Replaces the VPC associations of a private zone
             */
            vpcs?: components["schemas"]["VpcAssociation"][] | null;
        };
        /** ImportSummary */
        ImportSummary: {
            /**
             * Create
             * @default 0
             */
            create?: number;
            /**
             * Replace
             * @default 0
             */
            replace?: number;
            /**
             * Skip
             * @default 0
             */
            skip?: number;
            /**
             * Error
             * @default 0
             */
            error?: number;
        };
        /** ImportedRecordSet */
        ImportedRecordSet: {
            /** Line */
            line: number;
            /** Name */
            name: string;
            type: components["schemas"]["RecordType"];
            /** Ttl */
            ttl: number;
            /** Values */
            values: string[];
            /**
             * Status
             * @enum {string}
             */
            status: "create" | "replace" | "skip" | "error";
            /** Reason */
            reason?: string | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * @example demo@example.com
             */
            email: string;
            /** Password */
            password: string;
        };
        /** Page[HostedZoneSummary] */
        Page_HostedZoneSummary_: {
            /** Items */
            items: components["schemas"]["HostedZoneSummary"][];
            /**
             * Total
             * @description Number of items matching the query across all pages
             */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Pages */
            pages: number;
        };
        /** Page[RecordSetOut] */
        Page_RecordSetOut_: {
            /** Items */
            items: components["schemas"]["RecordSetOut"][];
            /**
             * Total
             * @description Number of items matching the query across all pages
             */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Pages */
            pages: number;
        };
        /** PublishedCredentials */
        PublishedCredentials: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * RecordSetInput
         * @description A complete record set, as accepted by create and by change batches.
         */
        RecordSetInput: {
            /**
             * Name
             * @description Relative to the zone (`www`), fully qualified, or empty / `@` for the apex
             * @default
             */
            name?: string;
            type: components["schemas"]["RecordType"];
            /**
             * Ttl
             * @description Seconds; required unless alias
             */
            ttl?: number | null;
            /**
             * Values
             * @description One entry per value; empty for alias
             * @default []
             */
            values?: string[];
            /** @default simple */
            routing_policy?: components["schemas"]["RoutingPolicy"];
            /** Set Identifier */
            set_identifier?: string | null;
            /** Weight */
            weight?: number | null;
            /** Region */
            region?: string | null;
            failover?: components["schemas"]["FailoverRole"] | null;
            geolocation?: components["schemas"]["GeoLocation"] | null;
            /** Health Check Id */
            health_check_id?: string | null;
            alias_target?: components["schemas"]["AliasTarget"] | null;
        };
        /** RecordSetOut */
        RecordSetOut: {
            /** Id */
            id: string;
            /** Zone Id */
            zone_id: string;
            /**
             * Name
             * @description Canonical FQDN with trailing dot
             * @example www.example.com.
             */
            name: string;
            type: components["schemas"]["RecordType"];
            /** Ttl */
            ttl: number | null;
            /** Values */
            values: string[];
            routing_policy: components["schemas"]["RoutingPolicy"];
            /** Set Identifier */
            set_identifier: string | null;
            /** Weight */
            weight: number | null;
            /** Region */
            region: string | null;
            failover: components["schemas"]["FailoverRole"] | null;
            geolocation: components["schemas"]["GeoLocation"] | null;
            /** Health Check Id */
            health_check_id: string | null;
            /** Alias */
            alias: boolean;
            alias_target: components["schemas"]["AliasTarget"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * RecordSetUpdate
         * @description Partial update; omitted fields keep their current value.
         */
        RecordSetUpdate: {
            /** Name */
            name?: string | null;
            type?: components["schemas"]["RecordType"] | null;
            /** Ttl */
            ttl?: number | null;
            /** Values */
            values?: string[] | null;
            routing_policy?: components["schemas"]["RoutingPolicy"] | null;
            /** Set Identifier */
            set_identifier?: string | null;
            /** Weight */
            weight?: number | null;
            /** Region */
            region?: string | null;
            failover?: components["schemas"]["FailoverRole"] | null;
            geolocation?: components["schemas"]["GeoLocation"] | null;
            /** Health Check Id */
            health_check_id?: string | null;
            alias_target?: components["schemas"]["AliasTarget"] | null;
        };
        /**
         * RecordType
         * @enum {string}
         */
        RecordType: "A" | "AAAA" | "CAA" | "CNAME" | "MX" | "NS" | "PTR" | "SOA" | "SRV" | "TXT";
        /**
         * RoutingPolicy
         * @enum {string}
         */
        RoutingPolicy: "simple" | "weighted" | "latency" | "failover" | "geolocation" | "multivalue";
        /** SessionOut */
        SessionOut: {
            user: components["schemas"]["UserOut"];
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** Tag */
        Tag: {
            /** Key */
            key: string;
            /**
             * Value
             * @default
             */
            value?: string;
        };
        /** TagList */
        TagList: {
            /** Tags */
            tags: components["schemas"]["Tag"][];
        };
        /** TagsUpdate */
        TagsUpdate: {
            /** Tags */
            tags: components["schemas"]["Tag"][];
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** Display Name */
            display_name: string;
            /** Account Id */
            account_id: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VpcAssociation */
        VpcAssociation: {
            /**
             * Vpc Id
             * @example vpc-0a1b2c3d4e5f67890
             */
            vpc_id: string;
            /**
             * Region
             * @example us-east-1
             */
            region: string;
        };
        /** ZoneFileImportRequest */
        ZoneFileImportRequest: {
            /** Content */
            content: string;
            /**
             * Dry Run
             * @description Validate and preview without saving
             * @default true
             */
            dry_run?: boolean;
            /**
             * Replace Existing
             * @description Overwrite record sets that already exist in the zone
             * @default false
             */
            replace_existing?: boolean;
        };
        /** ZoneFileImportResult */
        ZoneFileImportResult: {
            /** Dry Run */
            dry_run: boolean;
            /** Applied */
            applied: boolean;
            summary: components["schemas"]["ImportSummary"];
            /** Record Sets */
            record_sets: components["schemas"]["ImportedRecordSet"][];
            /**
             * Errors
             * @description Syntax errors, by zone file line
             */
            errors: components["schemas"]["ErrorDetail"][];
            /**
             * Change Id
             * @description ID of the change that imported the records; none for a preview
             */
            change_id?: string | null;
        };
        /**
         * ZoneType
         * @enum {string}
         */
        ZoneType: "public" | "private";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description The request violates a Route 53 rule */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not signed in or the session expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request body or parameters are malformed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too many failed attempts; see `Retry-After` */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Not signed in or the session expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    published_credentials: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishedCredentials"];
                };
            };
            /** @description The hosted zone or record does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_hosted_zones: {
        parameters: {
            query?: {
                /** @description Free-text search across the main columns */
                search?: string | null;
                /** @description Only zones of this type */
                type?: components["schemas"]["ZoneType"] | null;
                /** @description Property filter as `field:operator:value`, repeatable. Operators: eq, ne, contains, not_contains, starts_with, not_starts_with, gt, gte, lt, lte. */
                filter?: string[];
                /** @description Whether all filters must match or any of them */
                filter_mode?: "and" | "or";
                /** @description default (Route 53 order), name, type, description, id, created_by, record_count or created_at */
                sort?: string;
                /** @description Sort direction */
                order?: "asc" | "desc";
                /** @description 1-based page number */
                page?: number;
                /** @description Items per page */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_HostedZoneSummary_"];
                };
            };
            /** @description The request violates a Route 53 rule */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not signed in or the session expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request body or parameters are malformed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_hosted_zone: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HostedZoneCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HostedZoneDetail"];
                };
            };
            /** @description The request violates a Route 53 rule */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not signed in or the session expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request body or parameters are malformed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_hosted_zone: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Hosted zone ID */
                zone_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HostedZoneDetail"];
                };
            };
            /** @description Not signed in or the session expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The hosted zone does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_hosted_zone: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Hosted zone ID */
                zone_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not signed in or the session expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The hosted zone does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The change conflicts with existing data */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_hosted_zone: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Hosted zone ID */
                zone_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HostedZoneUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HostedZoneDetail"];
                };
            };
            /** @description The request violates a Route 53 rule */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not signed in or the session expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The hosted zone does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request body or parameters are malformed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_tags: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Hosted zone ID */
                zone_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagList"];
                };
            };
            /** @description Not signed in or the session expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The hosted zone does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replace_tags: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Hosted zone ID */
                zone_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagList"];
                };
            };
            /** @description The request violates a Route 53 rule */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not signed in or the session expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The hosted zone does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request body or parameters are malformed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_records: {
        parameters: {
            query?: {
                /** @description Free-text search across the main columns */
                search?: string | null;
                /** @description Only these record types; repeatable */
                type?: components["schemas"]["RecordType"][];
                /** @description Property filter as `field:operator:value`, repeatable. Operators: eq, ne, contains, not_contains, starts_with, not_starts_with, gt, gte, lt, lte. */
                filter?: string[];
                /** @description Whether all filters must match or any of them */
                filter_mode?: "and" | "or";
                /** @description default (Route 53 order), name, type, ttl, routing_policy, differentiator, set_identifier, alias, value, health_check_id, evaluate_target_health or id */
                sort?: string;
                /** @description Sort direction */
                order?: "asc" | "desc";
                /** @description 1-based page number */
                page?: number;
                /** @description Items per page */
                page_size?: number;
            };
            header?: never;
            path: {
                /** @description Hosted zone ID */
                zone_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_RecordSetOut_"];
                };
            };
            /** @description The request violates a Route 53 rule */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not signed in or the session expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The hosted zone or record does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request body or parameters are malformed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_record: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Hosted zone ID */
                zone_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordSetInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    /** @description ID of the change this request made; see `GET /changes/{change_id}` */
                    "X-Change-Id"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordSetOut"];
                };
            };
            /** @description The request violates a Route 53 rule */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not signed in or the session expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The hosted zone or record does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The change conflicts with existing data */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request body or parameters are malformed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    change_records: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Hosted zone ID */
                zone_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeBatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeBatchResult"];
                };
            };
            /** @description The request violates a Route 53 rule */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not signed in or the session expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The hosted zone or record does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request body or parameters are malformed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_record: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Record ID */
                record_id: string;
                /** @description Hosted zone ID */
                zone_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordSetOut"];
                };
            };
            /** @description Not signed in or the session expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The hosted zone or record does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_record: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Record ID */
                record_id: string;
                /** @description Hosted zone ID */
                zone_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    /** @description ID of the change this request made; see `GET /changes/{change_id}` */
                    "X-Change-Id"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The request violates a Route 53 rule */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not signed in or the session expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The hosted zone or record does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request body or parameters are malformed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_record: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Record ID */
                record_id: string;
                /** @description Hosted zone ID */
                zone_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordSetUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description ID of the change this request made; see `GET /changes/{change_id}` */
                    "X-Change-Id"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordSetOut"];
                };
            };
            /** @description The request violates a Route 53 rule */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not signed in or the session expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The hosted zone or record does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The change conflicts with existing data */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request body or parameters are malformed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    export_zone: {
        parameters: {
            query?: {
                format?: "bind" | "json";
            };
            header?: never;
            path: {
                /** @description Hosted zone ID */
                zone_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The exported zone as a file download */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": unknown;
                    "application/json": unknown;
                };
            };
            /** @description Not signed in or the session expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The hosted zone does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_zone_file: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Hosted zone ID */
                zone_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ZoneFileImportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZoneFileImportResult"];
                };
            };
            /** @description The request violates a Route 53 rule */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not signed in or the session expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The hosted zone does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request body or parameters are malformed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_change: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Change ID */
                change_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeInfo"];
                };
            };
            /** @description Not signed in or the session expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The hosted zone or record does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
